fix exception NoClassDefFoundError: gdscript/GdFileType
(cherry picked from commit 9dd8c090d964a7f30ead010f0119d1f2db50c490)

IJ-MR-163162

GitOrigin-RevId: b012cde9d20288f74b3003411d61ff7404d0a08e